### ISSUE TITLE
Build 1.1.1 is not updated on npmjs.com

### ISSUE THREAD

**Issue by meadowsjared** [QarthO/qHotkeys#5]
I'm sorry sir but the version `1.1.1` build on [npmjs](https://www.npmjs.com/package/qhotkeys) has the new `package.json` file, but it somehow is missing all the new functions like unregisterAll etc...

Steps to reproduce:
`npm i qhotkeys@1.1.1`

Trying to use it:
![image](https://github.com/user-attachments/assets/1a24fc71-9924-4013-94cf-e063f962345b)

You should notice the files in the `node_modules/dist` folder appear to be outdated possibly from version `1.0.15`, and is missing `unregister()` and `unregisterAll()` functions
index.d.ts
![image](https://github.com/user-attachments/assets/18cca41a-dac9-4f57-954f-3fe1f5aa9d95)
index.js
![image](https://github.com/user-attachments/assets/850044f2-2036-4615-8be8-2c9eac9e6f72)

Maybe with this latest build you forgot to run `npm run build` before publishing 🤔?

**Comment by meadowsjared** [comment]
note: I've created a [PR](https://github.com/QarthO/qHotkeys/pull/6) for auto-publishing, to remove some of the headaches of publishing 👍

**Comment by meadowsjared** [comment]
@QarthO thank you for **1.** fixing this, and **2.** making it easier to maintain in the future! 👍

**Comment by meadowsjared** [comment]
@QarthO I'm very sorry but the latest version (v1.1.3) is still broken, I'll comment over on that [PR](https://github.com/QarthO/qHotkeys/pull/6) for more detail

**Comment by QarthO** [comment]
Resolved. Thanks for letting me know. Sorry about all the hassle last couple of months. Will be more on top of it now

**Comment by meadowsjared** [comment]
All good man, thank you for making `qHotkeys` ❤️  (something I feel like electron **should** include already, but I feel they took a very foolish stance on the matter)!
